version: '3.8'
services:
        movie-analyst-api:
                build: ./api
                image: ${API_IMAGE}
                
                environment:
      			- DB_HOST=${DB_HOST}
      			- DB_USER=${DB_USER}
      			- DB_PASS=${DB_PASS}
      			- DB_NAME=${DB_NAME}
                        - BACKEND_PORT=${BACKEND_PORT}
                env_file:
                        - .env
                container_name: ${API_CONTAINER}
                ports:
                        - "3000:3000"
                restart: unless-stopped
                
                healthcheck:
                        test: curl --fail http://localhost:3000 || exit 1
                        interval: 60s
                        retries: 5
                        start_period: 20s
                        timeout: 10s
